{
    blogs{
        _id
        title
        text
        short_text
        imageURL
        author{
            _id
            first_name
        }
        category{
            title
        }
      comments{
        comment
        createdAt
        openToComment
        parent{
          _id
        }
        user{
          first_name
          last_name
        }
      }
    }
}