query getBlogs($categoryId :String){
  myData : blogs (category : $categoryId){
    ...blogFields
  }
}

fragment blogFields on BlogType {
        _id
        title
        text
        short_text
        imageURL
        author{
            _id
            first_name
        }
        category{
            title
        }
      comments{
        comment
        _id
        createdAt
        openToComment
        answers{
          comment
          createdAt
          user{
            first_name
            last_name
          }
        }
        user{
          first_name
          last_name
        }
      }
}