query getCourses($categoryId :String){
  myData : courses (category : $categoryId){
    ...courseFields
  }
}

fragment courseFields on CourseType {
        _id
        title
        text
        short_text
        imageURL
        category{
            title
        }
      comments{
        comment
        _id
        createdAt
        openToComment
        answers{
          _id
          comment
          createdAt
          user{
            first_name
            last_name
          }
        }
        user{
          first_name
          last_name
        }
      }
}