
query getProds($categoryId :String){
  myData : products (category : $categoryId){
    ...productFields
  }
}

fragment productFields on ProductType {
  _id
    title
    text
    imagesURL
    tags
    supplier{
      first_name
      last_name
    }
    category{
      _id
      title
    }
    features{
      length
      height
      width
      weight
    }
  comments{
        comment
        _id
        createdAt
        openToComment
        answers{
          _id
          comment
          createdAt
          user{
            first_name
            last_name
          }
        }
        user{
          first_name
          last_name
        }
      }
}