{
  products{
    _id
    title
    text
    imagesURL
    tags
    supplier{
      first_name
      last_name
    }
    category{
      _id
      title
    }
    features{
      length
      height
      width
      weight
    }
  }
}